# Generated by Django 4.1.4 on 2022-12-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
