# Generated by Django 4.1.4 on 2022-12-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_blood_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=100)),
                ('patient', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('3 PM', ' 3 PM'), ('3:30 PM', ' 3:30 PM'), ('4 PM', ' 4 PM'), ('4:30 PM', ' 4:30 PM'), ('5 PM', ' 5 PM'), ('5:30 PM', ' 5:30 PM'), ('6 PM', ' 6 PM'), ('6:30 PM', ' 6:30 PM'), ('7 PM', ' 7 PM')], max_length=100)),
                ('hb', models.FloatField(max_length=100)),
                ('bs', models.FloatField(max_length=100)),
                ('bmi', models.FloatField(max_length=100)),
            ],
        ),
    ]
