# Generated by Django 4.1.4 on 2022-12-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_patient_doctor_alter_patient_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
