# Generated by Django 4.1.4 on 2023-01-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_patient_doctor_alter_patient_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Appointment',
        ),
    ]
